apiVersion: app/v1
kind: Deployment
metadata:
  name: pokedex-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-ui
  template:
    metadata:
      labels:
        app: pokedex-ui
    spec:
      containers:
      - image: pokeapi:0.1
        name: pokedex-ui
        ports:
        - containerPort: 3000